### ISSUE TITLE
readonly 模式改进

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-form-renderer#184]
input & textarea 的 readonly 模式只考虑了 label 在 左侧的定位；当 label 在其他位置时就会很丑陋了。

建议用回 input & textarea，使用原生 readonly 属性。然后用如下 css 固定样式
```css
textarea[readonly] {
  border: 1px solid #dcdee6; // 只读状态不要有 focus 状态
}
```
![image](https://user-images.githubusercontent.com/19591950/81926802-235d0600-9615-11ea-93e9-21fb880876a8.png)
