### ISSUE TITLE
期望能够设置表单项目的顺序

### ISSUE THREAD

**Issue by qiaoqiao10001** [FEMessage/el-form-renderer#30]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
期望能对渲染的表单项目进行排序

**Describe alternatives you've considered**
例如以下的表单，现在是分成了左右两行；我需要按照这个顺序来显示，但是我现在必须使用2个form-renderer来显示；期望只使用一个来配置；
![image](https://user-images.githubusercontent.com/25581172/57213983-06155500-701b-11e9-9b16-b33d17e44db0.png)

**Additional context**
如题
现在的代码结构如下
![image](https://user-images.githubusercontent.com/25581172/57214015-1e856f80-701b-11e9-8acc-69b08725de76.png)

**Comment by levy9527** [comment]
请再提供多一点代码信息。`staffInfo` `staffInfoRight` 是什么

**Comment by qiaoqiao10001** [comment]
> 请再提供多一点代码信息。`staffInfo` `staffInfoRight` 是什么

这个基本信息 是通过两个formrenderer 渲染出来的， 左边是一个formrenderer，右边是一个，然后就出现了staffInfo & staffInfoRight

**Comment by donaldshen** [comment]
只需要设置
```css
.el-form {
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  width: $width;
  height: $height;
}
.el-form-item {
  width: 50%;
}
```
![image](https://user-images.githubusercontent.com/19591950/61350044-d0051480-a898-11e9-9005-40d30a41c664.png)
